sculpin_markdown:
    parser_class: Sculpin\Bundle\MarkdownBundle\PhpMarkdownExtraParser
    extensions: ['md']

sculpin_content_types:
    reports:
        type: path
        path: _report
        singular_name: report
        layout: report/single
        enabled: true
        taxonomies:
            - tags
            - category
        permalink: report/:slug_filename.html
    gctis:
      type: path
      path: _gcti
      singular_name: gcti
      layout: report/single
      enabled: true
      taxonomies:
          - tags
          - category
      permalink: gcti/:slug_filename.html

    booknames:
        type: path
        path: _bookname
        singular_name: bookname
        layout: report/single
        enabled: true
        permalink: bookname/:slug_filename.html

    posts:
        enabled: true
        type: path
        path: _post
        singular_name: post
        layout: report/single
        enabled: true
        permalink: post/:slug_filename.html

    wesleys:
        enabled: true
        type: path
        path: _wesley
        singular_name: wesley
        layout: report/singlewe
        enabled: true
        permalink: wesley/:slug_filename.html


services:
    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags:
             - { name: twig.extension }
